coverage:
  status:
    project:
      default:
        target: 90%
        threshold: 1%  # Allow 1% drop without failing
        base: auto  # Use auto base detection
        if_ci_failed: error  # Mark as error if CI fails
        informational: false  # Make this a required check
        only_pulls: false  # Show on all commits, not just PRs
    patch:
      default:
        target: 90%
        threshold: 1%
        base: pr  # Compare against PR base, not parent commit
        informational: false
        only_pulls: true  # Only run on PRs

comment:
  layout: "diff, flags, files"
  behavior: default
  require_changes: true

# GitHub-specific settings
github_checks:
  annotations: true  # Add line-by-line annotations

# How to handle PR base selection
codecov:
  branch: main  # Specify your default branch
  ci:
    - github.com  # Ensure GitHub CI is recognized

fixes:
  - "/var/snap/amazon-ssm-agent/[0-9]+/::"
