coverage:
  status:
    project:
      default:
        target: 90%
        threshold: 1%  # Allow 1% drop without failing
        if_ci_failed: error  # Mark as error if CI fails
        informational: false  # Make this a required check
    patch:
      default:
        target: 90%
        threshold: 1%
        informational: false

comment:
  layout: "diff, flags, files"

fixes:
  - "/var/snap/amazon-ssm-agent/[0-9]+/::"
