coverage:
  status:
    project:
      default:
        target: 90%
    patch:
      default:
        informational: true

comment:
  layout: "diff, flags, files"

fixes:
  - "/var/snap/amazon-ssm-agent/[0-9]+/::"
